name = "LavocDerma Cart Drawer"
client_id = "086b2759419dacc141d03852e017baad"
application_url = "https://cartapp-ten.vercel.app"
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://cartapp-ten.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/api/webhooks/app-uninstalled"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "bundleappstore-2.myshopify.com"
